/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __SharedMemoryUtilities_SharedMemory__
#define __SharedMemoryUtilities_SharedMemory__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jint JNICALL Java_SharedMemoryUtilities_SharedMemory_alloc (JNIEnv *env, jclass, jint, jint);
JNIEXPORT void JNICALL Java_SharedMemoryUtilities_SharedMemory_write (JNIEnv *env, jclass, jint, jint, jstring);
JNIEXPORT jstring JNICALL Java_SharedMemoryUtilities_SharedMemory_read (JNIEnv *env, jclass, jint, jint);
JNIEXPORT void JNICALL Java_SharedMemoryUtilities_SharedMemory_free (JNIEnv *env, jclass, jint);
JNIEXPORT void JNICALL Java_SharedMemoryUtilities_SharedMemory_displaySharedMemory (JNIEnv *env, jclass, jint);

#ifdef __cplusplus
}
#endif

#endif /* __SharedMemoryUtilities_SharedMemory__ */
