# centOS
CFLAGS=-g -Wall
libSharedMemory.so: SharedMemory.c
	gcc -o libSharedMemory.so SharedMemory.c -fPIC -shared -I /usr/lib/jvm/java-1.7.0-openjdk.x86_64/include -I /usr/lib/jvm/java-1.7.0-openjdk.x86_64/include/linux
